# Generated by Django 3.2.12 on 2023-05-20 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lang_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=200)),
                ('book_image', versatileimagefield.fields.VersatileImageField(upload_to='book_image')),
                ('book_hoverimage', versatileimagefield.fields.VersatileImageField(upload_to='book_image')),
                ('author_name', models.CharField(max_length=100)),
                ('del_price', models.CharField(max_length=50)),
                ('original_price', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Books')),
                ('details', models.TextField()),
                ('describtion', models.TextField()),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.lang_category')),
            ],
        ),
    ]
